version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.11
  slack: circleci/slack@4.4.2
  node: circleci/node@4.5.1
  mem: circleci/rememborb@0.0.1

parameters:
  alerts-slack-channel:
    type: string
    default: ppud-replacement-devs
  releases-slack-channel:
    type: string
    default: ppud-replacement-releases

jobs:
  deploy_to_manage_recalls:
    executor: hmpps/default_small
    parameters:
      env:
        type: string
    environment:
      KUBE_NAMESPACE_OVERRIDE: manage-recalls-<< parameters.env >>
    steps:
      - checkout
      - hmpps/k8s_setup:
          kube-namespace: KUBE_NAMESPACE_OVERRIDE
      - hmpps/install_helm
      - hmpps/install_aws_cli
      - mem/recall:
          env_var: APP_VERSION
      - deploy:
          name: Deploy to << parameters.env >>
          working_directory: helm_deploy
          environment:
            RELEASE_NAME: manage-recalls-error-pages
            CHART_NAME: manage-recalls-error-pages
            ENV_NAME: << parameters.env >>
          command: |
              # Show the context in use - just to check the namespace is correct
              kubectl config get-contexts

              # this is a hack to allow seeing the actual app version in the helm release metadata
              sed -i "s/appVersion:.*/appVersion: \"${APP_VERSION}\"/g" "${CHART_NAME}/Chart.yaml"

              # Install/update any chart dependencies.
              helm dependency update "${CHART_NAME}"

              HELM_ARGS=(--wait \
                --install \
                --reset-values \
                --timeout 5m \
                --history-max 10 \
                --values "values-${ENV_NAME}.yaml" \
                --set "generic-service.image.tag=${APP_VERSION}")

              helm upgrade "${RELEASE_NAME}" "${CHART_NAME}" "${HELM_ARGS[@]}"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/helm_lint:
          name: helm_lint

      - hmpps/build_docker:
          name: build_docker
          publish: false
          persist_container_image: true
          additional_docker_build_args: --build-arg BUILD_URL=${CIRCLE_BUILD_URL}

      - hmpps/trivy_pipeline_scan:
          name: trivy_scan_low_medium_cves
          fail_build: false
          cve_severities_to_check: UNKNOWN,LOW,MEDIUM
          requires:
            - build_docker

      - hmpps/trivy_pipeline_scan:
          name: trivy_scan
          requires:
            - build_docker

      - hmpps/publish_docker:
          name: publish_docker
          requires:
            - helm_lint
            - trivy_scan
          filters:
            branches:
              only:
                - main

      - hmpps/deploy_env:
          name: deploy_dev
          env: dev
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - publish_docker

      - deploy_to_manage_recalls:
          name: deploy_to_manage_recalls_dev
          env: dev
          context:
            - hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - publish_docker

      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev

      - hmpps/deploy_env:
          name: deploy_preprod
          env: preprod
          context:
            - hmpps-common-vars
            - manage-recalls-error-pages-preprod
          requires:
            - request-preprod-approval

      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod

      - hmpps/deploy_env:
          name: deploy_prod
          env: prod
          context:
            - hmpps-common-vars
            - manage-recalls-error-pages-prod
          requires:
            - request-prod-approval
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>

  security:
    triggers:
      - schedule:
          cron: "28 6 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
